[package]
name = "webapp"
version = "0.1.0"
authors = ["hg.king <hg_king@external.mckinsey.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
strum = "0.18"
strum_macros = "0.18"
serde = "1"
serde_derive = "1"
yew = "0.15"
wasm-bindgen = "0.2.62"
web-sys = "0.3.39"
